### ISSUE TITLE
Some files are missing in Skins

### ISSUE THREAD

**Issue by Mte90** [basxto/blackCortex#2]
In this folder Base.rte/GUIs/Skins/MainMenu there are some file missing that can be copied from Base.rte/GUIs/Skins/Base.

**Comment by basxto** [comment]
Which files are reported as missing?
I just added symbolic links for files that I saw being used somewhere.

**Comment by basxto** [comment]
Did you run the makefile?
I copy and convert some BMPs there from Base to MainMenu.
They get converted from 8bit BMP to truecolor (24bit) and I do that automated to avoid redundancy.
```make
skins=Cursive1 goldgui NeoSans pointer resize text tom_thumb_shadow Corsive2
...
.PHONY: skins
skins: $(foreach img,$(skins),$(mainskin)$(img).bmp)
...
$(mainskin)%.bmp: $(baseskin)%.bmp
	$(convert) "$<" -colorspace rgb -type truecolor "$@"
```

**Comment by Mte90** [comment]
Cursive1/2, pointer, resize as I can remember.
Dammit I forgot to add them in the ticket.
And yes I run make inside the folder but I can do another check.

**Comment by Mte90** [comment]
This time worked, I don't know why didn't the other time
